/* ----------------------------------------------------------------------------------------------Auteur--------------------------------------------------------------------------------*/
INSERT INTO AUTORS(ID_AUTORS ,NAME_AUTORS , SURNAME_AUTORS,  BIRTHDAY)
    VALUES (1 , 'Joël', 'DICKER',  '16/06/1985');
	
INSERT INTO AUTORS(ID_AUTORS ,NAME_AUTORS , SURNAME_AUTORS,  BIRTHDAY)
    VALUES (2 , 'Chu', 'GONG',  '23/10/1988');

INSERT INTO AUTORS(ID_AUTORS ,NAME_AUTORS , SURNAME_AUTORS,  BIRTHDAY)
    VALUES (3 , 'Adam', 'WOODWORTH',  '06/01/1976');
	
INSERT INTO AUTORS(ID_AUTORS ,NAME_AUTORS , SURNAME_AUTORS,  BIRTHDAY)
    VALUES (4 , 'Immanuel', 'KANT',  '22/04/1724');
	
INSERT INTO AUTORS(ID_AUTORS ,NAME_AUTORS , SURNAME_AUTORS,  BIRTHDAY)
    VALUES (5 , 'Pierre', 'BOUTRON',  '11/11/1947');
	
INSERT INTO AUTORS(ID_AUTORS ,NAME_AUTORS , SURNAME_AUTORS,  BIRTHDAY)
    VALUES (6 , 'Jean-Claude', 'NACHON',  '25/05/1963');
	
INSERT INTO AUTORS(ID_AUTORS ,NAME_AUTORS , SURNAME_AUTORS,  BIRTHDAY)
    VALUES (7 , 'Angélique', 'NACHON',  '09/04/1975');
	
INSERT INTO AUTORS(ID_AUTORS ,NAME_AUTORS , SURNAME_AUTORS,  BIRTHDAY)
    VALUES (8 , 'Arnaud', 'VIARD',  '22/08/1965');
	
INSERT INTO AUTORS(ID_AUTORS ,NAME_AUTORS , SURNAME_AUTORS,  BIRTHDAY)
    VALUES (9 , 'Benjamin', 'BIOLAY',  '24/01/1973');
	
INSERT INTO AUTORS(ID_AUTORS ,NAME_AUTORS , SURNAME_AUTORS,  BIRTHDAY)
    VALUES (10 , 'Georges', 'LAUTNER',  '24/01/1926');
	
INSERT INTO AUTORS(ID_AUTORS ,NAME_AUTORS , SURNAME_AUTORS,  BIRTHDAY)
    VALUES (11, 'Richard', 'CARON',  '30/12/1933');

INSERT INTO AUTORS(ID_AUTORS ,NAME_AUTORS , SURNAME_AUTORS,  BIRTHDAY)
    VALUES (12 , 'P.J', 'HOGAN',  '30/11/1962');
	
INSERT INTO AUTORS(ID_AUTORS ,NAME_AUTORS , SURNAME_AUTORS,  BIRTHDAY)
    VALUES (13 , 'Jarvis', 'TAVERNIER',  '01/01/1963');
	
INSERT INTO AUTORS(ID_AUTORS ,NAME_AUTORS , SURNAME_AUTORS,  BIRTHDAY)
    VALUES (14 , 'Kevin', 'MORBY',  '01/06/1958');
	
INSERT INTO AUTORS(ID_AUTORS ,NAME_AUTORS , SURNAME_AUTORS,  BIRTHDAY)
    VALUES (15 , 'Timothé', 'MERCADAL',  '29/12/1997');
	
INSERT INTO AUTORS(ID_AUTORS ,NAME_AUTORS , SURNAME_AUTORS,  BIRTHDAY)
    VALUES (16 , 'Katheryn', 'HUDSON',  '25/10/1984');
	
INSERT INTO AUTORS(ID_AUTORS ,NAME_AUTORS , SURNAME_AUTORS,  BIRTHDAY)
    VALUES (17 , 'David', 'CASTELLO-LOPES',  '16/09/1981');
	
INSERT INTO AUTORS(ID_AUTORS ,NAME_AUTORS , SURNAME_AUTORS,  BIRTHDAY)
    VALUES (18 , 'Kyan', 'JHOJANDI',  '29/10/1979');
	
INSERT INTO AUTORS(ID_AUTORS ,NAME_AUTORS , SURNAME_AUTORS,  BIRTHDAY)
    VALUES (19 , 'Cyprien', 'IOV',  '26/03/1983');
	
INSERT INTO AUTORS(ID_AUTORS ,NAME_AUTORS , SURNAME_AUTORS,  BIRTHDAY)
    VALUES (20 , 'Butters', 'PARKSOUTH',  '25/08/1991');
	
INSERT INTO AUTORS(ID_AUTORS ,NAME_AUTORS , SURNAME_AUTORS,  BIRTHDAY)
    VALUES (21 , 'Thibaut', 'GIRAUD',  '30/04/1987');

/* ----------------------------------------------------------------------------------------------EDITEUR--------------------------------------------------------------------------------*/
    
INSERT INTO EDITORS(NAME_EDITORS , ADRESSE , PHONE_NUMBER)
    VALUES ('Edition de Fallois', '22 Rue la Boétie 75008 Paris' ,  '01 42 66 91 95');
    
INSERT INTO EDITORS(NAME_EDITORS , ADRESSE , PHONE_NUMBER)
    VALUES ('DUNOD', '11 Rue Paul Bert 92247 Malakoff' ,  '01 41 23 66 00');

INSERT INTO EDITORS(NAME_EDITORS , ADRESSE , PHONE_NUMBER)
    VALUES ('EYROLLES', '55-57-61 Boulevard Saint-Germain 75005 Paris' ,  '03 21 79 56 75');

INSERT INTO EDITORS(NAME_EDITORS , ADRESSE , PHONE_NUMBER)
    VALUES ('DNC media', '93-2 Myeong Dong SEOUL' ,  '02 333 2514');

INSERT INTO EDITORS(NAME_EDITORS , ADRESSE , PHONE_NUMBER)
    VALUES ('Hachette', '58 Rue Jean Bleuzen 92170 Vanves' ,  '01 43 25 36 85');

INSERT INTO EDITORS(NAME_EDITORS , ADRESSE , PHONE_NUMBER)
    VALUES ('Expand Drama', '65 Rue de la gare 93200 SAINT-DENIS' ,  '04 85 84 14 01');

INSERT INTO EDITORS(NAME_EDITORS , ADRESSE , PHONE_NUMBER)
    VALUES ('Gloria films', '26 Rue de la Mairie, 75014 Paris' ,  '09 44 48 15 26');

INSERT INTO EDITORS(NAME_EDITORS , ADRESSE , PHONE_NUMBER)
    VALUES ('Les productions de la Lanterne', '8 AV LA PORTE DE MONTROUGE, 75014 PARIS' ,  '06 36 30 36 30');

INSERT INTO EDITORS(NAME_EDITORS , ADRESSE , PHONE_NUMBER)
    VALUES ('Gaumont Adresse', '30 avenue Charles de Gaulle Nantes 44300' ,  '05 83 12 32 55');

INSERT INTO EDITORS(NAME_EDITORS , ADRESSE , PHONE_NUMBER)
    VALUES ('Columbia pictures', 'Thalberg Building, 10202 West Washington Boulevard, Culver City, California , United States' ,  '08 98 48 16 67');

INSERT INTO EDITORS(NAME_EDITORS , ADRESSE , PHONE_NUMBER)
    VALUES ('Differ Ant', '4 rue du haut des sables, Poitiers 86000' ,  '05 49 48 47 46');

INSERT INTO EDITORS(NAME_EDITORS , ADRESSE , PHONE_NUMBER)
    VALUES ('Poney Gris', '10 rue de l étang , Plessis-Robinssons 12634' ,  '04 06 93 94 51');

INSERT INTO EDITORS(NAME_EDITORS , ADRESSE , PHONE_NUMBER)
    VALUES (' Virgin Records', '15 rue de l Hôtel Dieu, Poitiers 86000' ,  '05 49 45 30 00');

INSERT INTO EDITORS(NAME_EDITORS , ADRESSE , PHONE_NUMBER)
    VALUES ('CANAL+ France', '35 Rue de la Clairière Orléans' ,  '07 15 36 55 89 ');

INSERT INTO EDITORS(NAME_EDITORS , ADRESSE , PHONE_NUMBER)
    VALUES ('Youtube', '65 Rue du Moulin 75000 Paris' ,  '08 09 44 26 14 ');

INSERT INTO EDITORS(NAME_EDITORS , ADRESSE , PHONE_NUMBER)
    VALUES ('Tev & Louis', '901 Cherry Ave – San Bruno, CA 94066' ,  '1 650-253-0000');

INSERT INTO EDITORS(NAME_EDITORS , ADRESSE , PHONE_NUMBER)
    VALUES ('Vortex', 'Arte 8 r Marceau, 92130 Issy les Moulineaux' ,  '01 55 00 77 77');

/* ----------------------------------------------------------------------------------------------Emprunteur--------------------------------------------------------------------------------*/
    
INSERT INTO BORROWERS(ID_BORROWERS, NAME_BORROWERS, SURNAME_BORROWERS, ADRESSE, PHONE_NUMBER, NAME_CATEGORIE)
    VALUES (2, 'Richard', 'Arbani', '119 rue du chapeau', '07 52 17 58 40', 'Personnel');

INSERT INTO BORROWERS(ID_BORROWERS, NAME_BORROWERS, SURNAME_BORROWERS, ADRESSE, PHONE_NUMBER, NAME_CATEGORIE)
    VALUES (3, 'Grosse', 'Bertha', '27 boulevard Allemand', '06 06 06 06 06', 'Public');

INSERT INTO BORROWERS(ID_BORROWERS, NAME_BORROWERS, SURNAME_BORROWERS, ADRESSE, PHONE_NUMBER, NAME_CATEGORIE)
    VALUES (4, 'Gille', 'centzes', '65 rue du Lte Avince', '07 60 99 48 26', 'Professionnel');

INSERT INTO BORROWERS(ID_BORROWERS, NAME_BORROWERS, SURNAME_BORROWERS, ADRESSE, PHONE_NUMBER, NAME_CATEGORIE)
    VALUES (5, 'Marcel', 'Pontans', '77 rue du pont St Marc', '07 50 06 35 86', 'Public');

INSERT INTO BORROWERS(ID_BORROWERS, NAME_BORROWERS, SURNAME_BORROWERS, ADRESSE, PHONE_NUMBER, NAME_CATEGORIE)
    VALUES (6, 'David', 'Newell', '789 avenue de l`hôtel Aurore', '04 12 68 29 48', 'Personnel');

INSERT INTO BORROWERS(ID_BORROWERS, NAME_BORROWERS, SURNAME_BORROWERS, ADRESSE, PHONE_NUMBER, NAME_CATEGORIE)
    VALUES (7, 'Léa', 'Lanau', '231 boulevard de l`obellisque', '07 52 21 23 55', 'Public');

INSERT INTO BORROWERS(ID_BORROWERS, NAME_BORROWERS, SURNAME_BORROWERS, ADRESSE, PHONE_NUMBER, NAME_CATEGORIE)
    VALUES (8, 'Marine', 'Picon', '14 rue Jean-Charles Vaint', '06 30 51 45 26', 'Public');

INSERT INTO BORROWERS(ID_BORROWERS, NAME_BORROWERS, SURNAME_BORROWERS, ADRESSE, PHONE_NUMBER, NAME_CATEGORIE)
    VALUES (9, 'Aria', 'Maldin', '8 chemin de l`olivier', '08 09 77 15 26', 'Professionnel');

INSERT INTO BORROWERS(ID_BORROWERS, NAME_BORROWERS, SURNAME_BORROWERS, ADRESSE, PHONE_NUMBER, NAME_CATEGORIE)
    VALUES (10, 'Martin', 'Avok', '16 avenue point de croix', '04 44 59 28 17', 'Personnel');

INSERT INTO BORROWERS(ID_BORROWERS, NAME_BORROWERS, SURNAME_BORROWERS, ADRESSE, PHONE_NUMBER, NAME_CATEGORIE)
    VALUES (11, 'Arthur', 'Chevallais', '78 boulevard du vieux port', '08 09 75 15 29', 'Public');

INSERT INTO BORROWERS(ID_BORROWERS, NAME_BORROWERS, SURNAME_BORROWERS, ADRESSE, PHONE_NUMBER, NAME_CATEGORIE)
    VALUES (12, 'Elène', 'Francine', '11 chemin de l`ancien moulin', '05 22 64 18 22', 'Public');

INSERT INTO BORROWERS(ID_BORROWERS, NAME_BORROWERS, SURNAME_BORROWERS, ADRESSE, PHONE_NUMBER, NAME_CATEGORIE)
    VALUES (13, 'Esteban', 'Lovreau', '98 rue du potiron', '07 09 88 51 88', 'Public');
 
INSERT INTO BORROWERS(ID_BORROWERS, NAME_BORROWERS, SURNAME_BORROWERS, ADRESSE, PHONE_NUMBER, NAME_CATEGORIE)
    VALUES (14, 'Anaïs', 'Sarone', '191 rue du pont St Marc', '07 88 09 77 48', 'Personnel');

INSERT INTO BORROWERS(ID_BORROWERS, NAME_BORROWERS, SURNAME_BORROWSER, ADRESSE, PHONE_NUMBER, NAME_CATEGORIE)
    VALUES (15, 'Alain', 'Tarn', '142 rue du petit pont', '02 52 68 54 25', 'Professionnel');